version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Maintain dependencies for PHP (Backend)
  - package-ecosystem: "composer"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for JS/TS (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
