upload_max_filesize = 40M
post_max_size = 40M
memory_limit = 512M
max_execution_time = 60      ; Réduit de 600s à 60s pour prévenir les DDoS lents
expose_php = Off             ; Cache la version PHP aux attaquants
session.cookie_secure = 1    ; Force le HTTPS pour les cookies de session bas niveau
session.cookie_httponly = 1  ; Bloque les accès de scripts JS aux cookies
session.use_strict_mode = 1  ; Protège contre Session Fixation

; Opcache (optimisé pour la Prod)
opcache.enable=0
opcache.memory_consumption=256
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0 ; Pas de vérif constante (meilleur mode prod)
